///////////////////////////////////////////////////////////
//  ResponseOperacionBE.cs
//  Implementation of the Class ResponseOperacionBE
//  Generated by Enterprise Architect
//  Created on:      08-feb.-2017 10:57:31
//  Original author: jfloresn
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Common.Comun
{ 
	public class ResponseOperacionBE {

		private OperacionType attr_OperacionType;
        private OperacionType m_OperacionType;
        private DataTableResponse atr_DataTableResponse;

		public ResponseOperacionBE(){

		}

		~ResponseOperacionBE(){

		}

		public OperacionType OperacionType{
			get{
				return attr_OperacionType;
			}
			set{
				attr_OperacionType = value;
			}
		}


        public DataTableResponse DataTableResponse
        {
			get{
                return atr_DataTableResponse;
			}
			set{
                atr_DataTableResponse = value;
			}
		}
        

		public List<ErrorForm> errorForms { get; set; }


	}//end ResponseOperacionBE


	public class ErrorForm { 
	
		public string propiedad { get; set; }
		public string mensaje { get; set; }
	}


}//end namespace Type