//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAgents.Xmarket.XmarketServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmarketServices.IBackendService")]
    public interface IBackendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/ExecuteCommand", ReplyAction="http://tempuri.org/IBackendService/ExecuteCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommandContracts.Common.CommandFault), Action="http://tempuri.org/IBackendService/ExecuteCommandCommandFaultFault", Name="CommandFault", Namespace="http://schemas.datacontract.org/2004/07/CommandContracts.Common")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.ActualizarProductoCarritoCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.EliminarProductoCarritoCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.CarritoAgregarCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.CarritoRegistrarCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Cliente.RegistrarDireccionCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Cuenta.ValidarUsuarioCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.General.CuentaCrearModificarCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Contactenos.ContactenosRegistrarCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Sesion.CrearSesionCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Pedido.RegistrarClienteContactoCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Pedido.RegistrarPedidoCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Pedido.RegistrarClienteSinSesionCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Contactenos.Output.ContactenosRegistrarOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Cliente.Output.RegistrarDireccionOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Sesion.Output.CrearSesionOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.ActualizarProductoCarritoOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.EliminarProductoCarritoOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.CarritoAgregarOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.CarritoRegistrarOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.RegistrarPedidoOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.Carrito.Output.RegistrarClienteSinSesionOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.General.Output.ValidarUsuarioOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommandContracts.Xmarket.General.Output.CuentaCrearModificarOutput))]
        CommandContracts.Common.CommandResult ExecuteCommand(CommandContracts.Common.Command command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/ExecuteCommand", ReplyAction="http://tempuri.org/IBackendService/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<CommandContracts.Common.CommandResult> ExecuteCommandAsync(CommandContracts.Common.Command command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/ExecuteQuery", ReplyAction="http://tempuri.org/IBackendService/ExecuteQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Categoria.Parameters.ListarCategoriaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Parameters.ListarMenusxRolesAdminParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Parameters.ListarMenusxRolesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Parameters.VerificarOpcionesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Parameters.LeerEspecialidadParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Parameters.ListarTodoEspecialidadParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Parameters.ListarEspecialidadParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Account.Parameters.ObtenerUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Account.Parameters.ObtenerUsuarioParameter1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Producto.Parameters.ListarProductoPorMarcaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Producto.Parameters.ListarProductoPorCategoriaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Carrito.Parameters.LeerCarritoDetalleParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Carrito.Parameters.ListarCarritoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Marca.Parameters.ListarMarcaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.ListarDistritoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.AreaGeneralParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.DashboardUltimoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.ListarProvinciaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.ObtenerCorrelativoNotifParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.BuscarTodoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.ListarDepartamentosParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Parameters.ObtenerCorrelativoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Parameters.LeerEditorialParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Parameters.ListarTodoEditorialParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Parameters.ListarEditorialParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.ObtenerDatosConexionParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Parameters.LeerColeccionParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Parameters.ColeccionListarParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Parameters.ColeccionHomeParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.AutorizacionRolParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.BuscarPaginasParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.BuscarSistemasParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarAutorizadorAreaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarOpcionesPaginaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarPaginaRolParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarTipoMenuParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerOpcionesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarOpcionesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarRolesDashBoardParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarRolesTodoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerRolParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarUsuarioAreaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarUsuariosDashBoardParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarUsuariosPorAreaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.DesbloquearUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.EliminarPaginaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.EliminarRolParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.EliminarUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.EncriptarPasswordParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.GenerarPasswordParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarClientesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarPaginasPadreParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarPaginasParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarRolesAsignablesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarRolesParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarSistemasParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ListarUsuariosParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerDatosBasicosUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerPaginaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerPasswordPorUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerPasswordParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ObtenerSistemaParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Parameters.ValidarExisteUsuarioParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Parameters.ClienteDireccionLeerParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Parameters.ClienteDireccionListarParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Parameters.ClienteLeerCorreoParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Parameters.ClienteLeerParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Parameters.ClienteLoginParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Parameters.BookLeerParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Parameters.BookListarParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Parameters.BookFiltroParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Parametro.Parameters.ListarParametrosParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Banner.Parameters.BannerListarParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Parametro.Result.ListarParametrosResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.DashboardUltimoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.AreaGeneralResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.ListarDistritoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.ListarProvinciaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.ObtenerCorrelativoNotifResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.BuscarTodoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.ListarDepartamentosResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.General.Result.ObtenerCorrelativoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Carrito.Result.LeerCarritoDetalleResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Carrito.Result.ListarCarritoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Results.ListarMenusxRolesAdminResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Results.ListarMenusxRolesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.Seguridad.Results.VerificarOpcionesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Banner.Results.BannerListarResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Result.ClienteDireccionLeerResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Result.ClienteDireccionListarResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Result.ClienteLeerCorreoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Result.ClienteLeerResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Cliente.Result.ClienteLoginResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Result.LeerEspecialidadResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Result.ListarTodoEspecialidadResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Especialidad.Result.ListarEspecialidadResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Result.BookLeerResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Result.BookListarResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Book.Result.BookFiltroResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Producto.Result.ListarProductoPorMarcaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Producto.Result.ListarProductoPorCategoriaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Result.LeerColeccionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Result.ColeccionListarResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Coleccion.Result.ColeccionHomeResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Marca.Result.ListarMarcaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.AutorizacionRolResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.EliminarPaginaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.BuscarPaginasResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.BuscarSistemasResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarPaginaRolResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarOpcionesPaginasResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarTipoMenuResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerPasswordPorUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.EliminarUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.EncriptarPasswordResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.GenerarPasswordResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarPaginasPadreResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarPaginasResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarRolesAsignablesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarSistemasResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarUsuarioAreaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarUsuariosDashBoardResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarUsuariosResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerDatosBasicosUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerPasswordResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerSistemaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ValidarExisteUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarAutorizadorPorAreaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerOpcionesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarOpcionesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarRolesDashBoardResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarRolesTodoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerRolResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarUsuariosPorAreaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.DesbloquearUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.EliminarRolResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarClientesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ListarRolesResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Seguridad.Result.ObtenerPaginaResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Common.ObtenerDatosConexionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Account.Results.ObtenerUsuarioResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Account.Results.ObtenerUsuarioResult1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Result.LeerEditorialResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Result.ListarTodoEditorialResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Editorial.Result.ListarEditorialResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(QueryContracts.Xmarket.Categoria.Result.ListarCategoriaResult))]
        QueryContracts.Common.QueryResult ExecuteQuery(QueryContracts.Common.QueryParameter parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/ExecuteQuery", ReplyAction="http://tempuri.org/IBackendService/ExecuteQueryResponse")]
        System.Threading.Tasks.Task<QueryContracts.Common.QueryResult> ExecuteQueryAsync(QueryContracts.Common.QueryParameter parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackendServiceChannel : ServiceAgents.Xmarket.XmarketServices.IBackendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackendServiceClient : System.ServiceModel.ClientBase<ServiceAgents.Xmarket.XmarketServices.IBackendService>, ServiceAgents.Xmarket.XmarketServices.IBackendService {
        
        public BackendServiceClient() {
        }
        
        public BackendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommandContracts.Common.CommandResult ExecuteCommand(CommandContracts.Common.Command command) {
            return base.Channel.ExecuteCommand(command);
        }
        
        public System.Threading.Tasks.Task<CommandContracts.Common.CommandResult> ExecuteCommandAsync(CommandContracts.Common.Command command) {
            return base.Channel.ExecuteCommandAsync(command);
        }
        
        public QueryContracts.Common.QueryResult ExecuteQuery(QueryContracts.Common.QueryParameter parameter) {
            return base.Channel.ExecuteQuery(parameter);
        }
        
        public System.Threading.Tasks.Task<QueryContracts.Common.QueryResult> ExecuteQueryAsync(QueryContracts.Common.QueryParameter parameter) {
            return base.Channel.ExecuteQueryAsync(parameter);
        }
    }
}
