///////////////////////////////////////////////////////////
//  RequestOperacionBE.cs
//  Implementation of the Class RequestOperacionBE
//  Generated by Enterprise Architect
//  Created on:      08-feb.-2017 10:57:31
//  Original author: jfloresn
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Xmarket.Type
{
	public class RequestOperacionBE {

		private OperacionType atr_OperacionType;
        private OperacionType m_OperacionType;
        private DataTableRequest atr_DataTableRquest;

		public RequestOperacionBE(){

		}

		~RequestOperacionBE(){

		}

		public OperacionType OperacionType{
			get{
				return atr_OperacionType;
			}
			set{
				atr_OperacionType = value;
			}
		}

		public DataTableRequest DataTableRquest{
			get{
				return atr_DataTableRquest;
			}
			set{
				atr_DataTableRquest = value;
			}
		}

	}//end RequestOperacionBE

}//end namespace Type